version: "3.3"
services:
  service:
    image: indralab/indra_world
    ports:
      - "8001:8000"
    env_file: indra_world.env
    entrypoint: gunicorn -w 1 -b :8000 -t 600 indra_world.service.app:app
  db:
    image: indralab/indra_world_db
    ports:
      - "5435:5432"
    env_file: indra_world_db.env
