import os
import logging
import argparse
from flask import jsonify, abort, Response, Flask, render_template, request, \
    redirect, session
from flask_wtf import FlaskForm
from wtforms import SubmitField, validators, SelectMultipleField, DateField, \
    StringField
from flask_bootstrap import Bootstrap

from indra.pipeline import AssemblyPipeline
from indra_wm_service.assembly.dart import process_reader_outputs
from indra_wm_service.live_curation import Corpus

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ASSEMBLY_JSON = os.path.join(HERE, 'default_pipeline.json')


logger = logging.getLogger('indra_wm_service.assembly_dashboard')
app = Flask(__name__)
app.config['SECRET_KEY'] = 'dev_key'
Bootstrap(app)


reader_names = [('eidos', 'eidos'),
                ('hume', 'hume'),
                ('cwms', 'cwms'),
                ('sofia', 'sofia')]


class RunAssemblyForm(FlaskForm):
    after_date = DateField(label='After date')
    before_date = DateField(label='Before date')
    readers = SelectMultipleField(label='Readers',
                                  id='reader-select',
                                  choices=reader_names,
                                  validators=[validators.unicode_literals])
    corpus_id = StringField(label='Corpus key')
    submit_button = SubmitField('Run assembly')


@app.route('/', methods=['GET'])
def index():
    run_assembly_form = RunAssemblyForm()
    kwargs = {'run_assembly_form': run_assembly_form}
    return render_template('index.html', **kwargs)


@app.route('/run_assembly', methods=['POST'])
def run_assembly():
    readers = request.form.getlist('readers')
    readers = readers if readers else None
    after_date = request.form.get('after_date')
    before_date = request.form.get('before_date')
    corpus_id = request.form.get('corpus_id')
    from indra.literature import dart_client
    timestamp = None if (not before_date and not after_date) else {}
    if after_date:
        timestamp['after'] = after_date
    if before_date:
        timestamp['before'] = before_date
    logger.info('Fetching reader output for readers %s and dates %s' %
                (str(readers), str(timestamp)))
    reader_outputs = dart_client.get_reader_outputs(readers, timestamp=timestamp)
    logger.info('Processing reader output...')
    stmts = process_reader_outputs(reader_outputs)
    logger.info('Got a total of %s statements' % len(stmts))

    pipeline = AssemblyPipeline.from_json_file(DEFAULT_ASSEMBLY_JSON)
    assembled_stmts = pipeline.run(stmts)

    meta_data = {
        'corpus_id': corpus_id,
        # Make this an argument
        'description':
            ('This corpus was generated by assembling reader output '
             'via the INDRA Assembly Dashboard.'),
        # TODO: make this an argument
        'display_name': corpus_id,
        # TODO: fix this
        'readers': readers,
        'assembly': {
            'level': 'grounding',
            'grounding_threshold': 0.7,
        },
        'num_statements': len(assembled_stmts),
        # TODO: fix this
        'num_documents': 1
    }

    corpus = Corpus(corpus_id=corpus_id,
                    statements=assembled_stmts,
                    raw_statements=stmts,
                    meta_data=meta_data)
    corpus.s3_put()
    return 'Assembly complete'



if __name__ == '__main__':
    # Process arguments
    parser = argparse.ArgumentParser(
        description='Choose a corpus for live curation.')
    parser.add_argument('--host', default='0.0.0.0')
    parser.add_argument('--port', default=8001, type=int)
    args = parser.parse_args()

    # Run the app
    app.run(host=args.host, port=args.port, threaded=False)
