name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install -e .[tests,eidos_offline]
        wget -nv https://bigmech.s3.amazonaws.com/travis/eidos.jar
        wget -nv https://bigmech.s3.amazonaws.com/travis/cache.zip
        cd /home/runner/work/indra_world/indra_world
        unzip cache.zip
    - name: Run unit tests
      run: |
        export NOSEATTR="!notravis"
        export INDRA_WM_CACHE="."
        export INDRA_WM_SERVICE_DB='sqlite:///:memory:'
        nosetests indra_world/tests -a $NOSEATTR -v --exclude='.*eidos.*' --with-coverage --cover-inclusive --cover-package=indra_world
        export EIDOSPATH=`pwd`/eidos.jar
        export CLASSPATH=$EIDOSPATH
        nosetests -v -a $NOSEATTR indra_world/tests/test_eidos.py
